=== beejhuff/magento2-acceptance-test-framework/src/Magento/AcceptanceTestFramework/DataGenerator/etc/DataProfileSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="config">
        <xs:annotation>
            <xs:documentation>
                The root element for configuration data.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element type="entityType" name="entity" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>
                            An element that contains configuration array containing all Entity elements.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="entityType">
        <xs:sequence>
            <xs:element type="xs:string" name="dataConfig" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>
                        DataConfig elements.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="dataObjectType" name="dataObject" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>
                        DataObject elements.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name">
            <xs:annotation>
                <xs:documentation>
                    Name of the Entity.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute type="xs:string" name="type">
            <xs:annotation>
                <xs:documentation>
                    Node containing the exact name of Entity type. Used later to find specific Persistence Layer Model
                    class.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="dataObjectType">
        <xs:sequence>
            <xs:element name="data" type="dataType" maxOccurs="unbounded" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>
                        Element containing Data/Value pair.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="assert" type="xs:string" maxOccurs="unbounded" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>
                        Name of Assert.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name">
            <xs:annotation>
                <xs:documentation>
                    Name of the DataObject element.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="dataType">
        <xs:attribute type="xs:string" name="key" use="optional">
            <xs:annotation>
                <xs:documentation>
                    Key attribute of data/value pair.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== beejhuff/magento2-acceptance-test-framework/src/Magento/AcceptanceTestFramework/DataProfile/Test/etc/data.xml
<?xml version="1.0" encoding="UTF-8"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../DataGenerator/etc/DataProfileSchema.xsd">
        <entity name="CustomerEntityOne" type="Website">
            <dataConfig>simpleConfiguration</dataConfig>
            <dataConfig>regressionConfiguration</dataConfig>
              <dataObject name="Personal">
                 <data key="FirstName">FirstNameData</data>
                 <data key="LastName">LastName</data>
                 <data key="Address">Address</data>
                 <data key="DateOfBirth">01/01/1990</data>
                 <assert>AssertNumberOne</assert>
                 <assert>AssertNumberTwo</assert>
              </dataObject>
              <dataObject name="Billing">
                 <data key="FirstName">adsfsdf</data>
                 <data key="LastName">fsdfs</data>
                 <data key="Address">asdfasdfsdf</data>
                 <assert>AssertNumberOne</assert>
                 <assert>AssertNumberTwo</assert>
                 <assert>AssertNumberThree</assert>
               </dataObject>
        </entity>
</config>
